[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[variables]
FALKORDB_HOST = "falkordb.railway.internal"
FALKORDB_PORT = "6379"
FALKORDB_PASSWORD = "848i4g64jptrctjs"
GRAPH_NAME = "agentsmith"
DEBUG = "true"
API_KEY_OPENROUTER = "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"
